In [1]:
import os
import matplotlib.pyplot as plt
import cv2
import numpy as np
import pandas as pd
from PIL import Image, ImageStat

In [2]:
path = 'data/'
df = pd.DataFrame(pd.read_csv(path+'data.csv'))
df = df[df['PhotoType']=='УФ']
df = df.loc[:,['Folder','Id','Ruin','Saturation']]

In [3]:
print(df[df['Saturation']=='не опред.'].count())
print(df[df['Saturation']!='не опред.'].count())

Folder        2298
Id            2298
Ruin          2298
Saturation    2298
dtype: int64
Folder        909
Id            909
Ruin          909
Saturation    909
dtype: int64


In [4]:
oil_indices = []
for row in df.itertuples():
    if row[4] == 'не опред.':
        oil_indices.append(row[0])
drop_indices = np.random.choice(oil_indices, 1389, replace=False)
df  = df.drop(drop_indices)

In [19]:
def get_oil_feature(img):
    img_hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    pil_img = Image.fromarray(img_hsv)
    mean_hue, mean_sat, mean_val = ImageStat.Stat(pil_img).mean
    dark = (0, 0, 85+mean_val/3) 
    light = (255, 255, 255)
    img_gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    mask_yel = cv2.inRange(img_hsv, dark, light)
    img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    img_yel = cv2.bitwise_and(img_gray, img_gray, mask=mask_yel)
    size = len(img) * len(img[0])
    area = sum([sum([0 if pxl == 0 else 1 for pxl in row])for row in img_yel])
    feature = {}
    feature['area'] = area / size
    feature['mean'] = sum([sum(row) for row in img_yel]) / (area*mean_val)
    feature['hue'] = mean_hue
    feature['sat'] = mean_sat
    feature['val'] = mean_val
    return feature

In [20]:
oil_features=[]

i = 1
for row in df.itertuples():
    img = plt.imread(path+row[1]+'/data/'+str(row[2])+'.jpeg', 1)
    feature = get_oil_feature(img)
    if row[3] == 'разрушен':
        feature['ruin'] = 2
    elif row[3] == 'не разрушен':
        feature['ruin'] = 0
    else:
        feature['ruin'] = 1
    oil_features.append(feature)
    print(str(i)+'/1818')
    i += 1

df['oil_features'] = oil_features
df.head(50)

1/1818
2/1818
3/1818
4/1818
5/1818
6/1818
7/1818
8/1818
9/1818
10/1818
11/1818
12/1818
13/1818
14/1818
15/1818
16/1818
17/1818
18/1818
19/1818
20/1818
21/1818
22/1818
23/1818
24/1818
25/1818
26/1818
27/1818
28/1818
29/1818
30/1818
31/1818
32/1818
33/1818
34/1818
35/1818
36/1818
37/1818
38/1818
39/1818
40/1818
41/1818
42/1818
43/1818
44/1818
45/1818
46/1818
47/1818
48/1818
49/1818
50/1818
51/1818
52/1818
53/1818
54/1818
55/1818
56/1818
57/1818
58/1818
59/1818
60/1818
61/1818
62/1818
63/1818
64/1818
65/1818
66/1818
67/1818
68/1818
69/1818
70/1818
71/1818
72/1818
73/1818
74/1818
75/1818
76/1818
77/1818
78/1818
79/1818
80/1818
81/1818
82/1818
83/1818
84/1818
85/1818
86/1818
87/1818
88/1818
89/1818
90/1818
91/1818
92/1818
93/1818
94/1818
95/1818
96/1818


/usr/lib/python3.7/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


97/1818
98/1818
99/1818
100/1818
101/1818
102/1818
103/1818
104/1818
105/1818
106/1818
107/1818
108/1818
109/1818
110/1818
111/1818
112/1818
113/1818
114/1818
115/1818
116/1818
117/1818
118/1818
119/1818
120/1818
121/1818
122/1818
123/1818
124/1818
125/1818
126/1818
127/1818
128/1818
129/1818
130/1818
131/1818
132/1818
133/1818
134/1818
135/1818
136/1818
137/1818
138/1818
139/1818
140/1818
141/1818
142/1818
143/1818
144/1818
145/1818
146/1818
147/1818
148/1818
149/1818
150/1818
151/1818
152/1818
153/1818
154/1818
155/1818
156/1818
157/1818
158/1818
159/1818
160/1818
161/1818
162/1818
163/1818
164/1818
165/1818
166/1818
167/1818
168/1818
169/1818
170/1818
171/1818
172/1818
173/1818
174/1818
175/1818
176/1818
177/1818
178/1818
179/1818
180/1818
181/1818
182/1818
183/1818
184/1818
185/1818
186/1818
187/1818
188/1818
189/1818
190/1818
191/1818
192/1818
193/1818
194/1818
195/1818
196/1818
197/1818
198/1818
199/1818
200/1818
201/1818
202/1818
203/1818
204/1818
205/1818
206/1818
207/1818
208/

1007/1818
1008/1818
1009/1818
1010/1818
1011/1818
1012/1818
1013/1818
1014/1818
1015/1818
1016/1818
1017/1818
1018/1818
1019/1818
1020/1818
1021/1818
1022/1818
1023/1818
1024/1818
1025/1818
1026/1818
1027/1818
1028/1818
1029/1818
1030/1818
1031/1818
1032/1818
1033/1818
1034/1818
1035/1818
1036/1818
1037/1818
1038/1818
1039/1818
1040/1818
1041/1818
1042/1818
1043/1818
1044/1818
1045/1818
1046/1818
1047/1818
1048/1818
1049/1818
1050/1818
1051/1818
1052/1818
1053/1818
1054/1818
1055/1818
1056/1818
1057/1818
1058/1818
1059/1818
1060/1818
1061/1818
1062/1818
1063/1818
1064/1818
1065/1818
1066/1818
1067/1818
1068/1818
1069/1818
1070/1818
1071/1818
1072/1818
1073/1818
1074/1818
1075/1818
1076/1818
1077/1818
1078/1818
1079/1818
1080/1818
1081/1818
1082/1818
1083/1818
1084/1818
1085/1818
1086/1818
1087/1818
1088/1818
1089/1818
1090/1818
1091/1818
1092/1818
1093/1818
1094/1818
1095/1818
1096/1818
1097/1818
1098/1818
1099/1818
1100/1818
1101/1818
1102/1818
1103/1818
1104/1818
1105/1818
1106/1818


Folder       Id         Ruin                Saturation  \
1    Unload1  1000001  не разрушен           нефтенасыщенные   
3    Unload1  1000003  не разрушен           нефтенасыщенные   
5    Unload1  1000005  не разрушен                 не опред.   
7    Unload1  1000007  не разрушен                 не опред.   
9    Unload1  1000009  не разрушен                 не опред.   
11   Unload1  1000011  не разрушен     слабо нефтенасыщенные   
13   Unload1  1000013  не разрушен     слабо нефтенасыщенные   
15   Unload1  1000015  не разрушен     слабо нефтенасыщенные   
17   Unload1  1000017  не разрушен  пятнисто нефтенасыщенные   
19   Unload1  1000019  не разрушен     слабо нефтенасыщенные   
21   Unload1  1000021  не разрушен     слабо нефтенасыщенные   
23   Unload1  1000023  не разрушен  пятнисто нефтенасыщенные   
25   Unload1  1000025  не разрушен     слабо нефтенасыщенные   
27   Unload1  1000027  не разрушен     слабо нефтенасыщенные   
31   Unload1  1000031  не разрушен     слабо нефтенасыщенные   
33   Unload1  1000033  не разрушен     слабо нефтенасыщенные   
35   Unload1  1000035  не разрушен     слабо нефтенасыщенные   
37   Unload1  1000037  не разрушен     слабо нефтенасыщенные   
39   Unload1  1000039  не разрушен     слабо нефтенасыщенные   
45   Unload1  1000045  не разрушен     слабо нефтенасыщенные   
47   Unload1  1000047  не разрушен  пятнисто нефтенасыщенные   
49   Unload1  1000049  не разрушен  пятнисто нефтенасыщенные   
51   Unload1  1000051  не разрушен  пятнисто нефтенасыщенные   
53   Unload1  1000053  не разрушен  пятнисто нефтенасыщенные   
55   Unload1  1000055  не разрушен  пятнисто нефтенасыщенные   
57   Unload1  1000057  не разрушен     слабо нефтенасыщенные   
59   Unload1  1000059  не разрушен     слабо нефтенасыщенные   
61   Unload1  1000061  не разрушен  пятнисто нефтенасыщенные   
63   Unload1  1000063  не разрушен  пятнисто нефтенасыщенные   
65   Unload1  1000065  не разрушен     слабо нефтенасыщенные   
67   Unload1  1000067  не разрушен     слабо нефтенасыщенные   
71   Unload1  1000071  не разрушен                 не опред.   
73   Unload1  1000073  не разрушен     слабо нефтенасыщенные   
75   Unload1  1000075  не разрушен     слабо нефтенасыщенные   
77   Unload1  1000077  не разрушен     слабо нефтенасыщенные   
79   Unload1  1000079  не разрушен  пятнисто нефтенасыщенные   
81   Unload1  1000081  не разрушен  пятнисто нефтенасыщенные   
83   Unload1  1000083  не разрушен     слабо нефтенасыщенные   
85   Unload1  1000085  не разрушен                 не опред.   
87   Unload1  1000087  не разрушен     слабо нефтенасыщенные   
89   Unload1  1000089  не разрушен     слабо нефтенасыщенные   
91   Unload1  1000091  не разрушен  пятнисто нефтенасыщенные   
93   Unload1  1000093  не разрушен  пятнисто нефтенасыщенные   
99   Unload1  1000099  не разрушен  пятнисто нефтенасыщенные   
105  Unload1  1000105  не разрушен  пятнисто нефтенасыщенные   
107  Unload1  1000107  не разрушен  пятнисто нефтенасыщенные   
109  Unload1  1000109  не разрушен  пятнисто нефтенасыщенные   
111  Unload1  1000111  не разрушен  пятнисто нефтенасыщенные   
113  Unload1  1000113  не разрушен  пятнисто нефтенасыщенные   
115  Unload1  1000115  не разрушен  пятнисто нефтенасыщенные   

                                          oil_features  
1    {'area': 0.25286157906333273, 'mean': 1.569056...  
3    {'area': 0.3950372089684382, 'mean': 1.4381886...  
5    {'area': 0.01965313659085387, 'mean': 5.076592...  
7    {'area': 0.053690314732963214, 'mean': 3.53246...  
9    {'area': 0.014285466457720131, 'mean': 4.53809...  
11   {'area': 0.46674449384056743, 'mean': 1.153790...  
13   {'area': 0.24416340129988973, 'mean': 1.516136...  
15   {'area': 0.6439285714285714, 'mean': 1.1406842...  
17   {'area': 0.048266871165644175, 'mean': 3.15229...  
19   {'area': 0.6391980767854984, 'mean': 1.0862742...  
21   {'area': 0.6777157743391177, 'mean': 1.0867414...  
23   {'area': 0.16594600911534416, 'mean': 2.476888...  


In [21]:
X = np.array([list(feature.values()) for feature in df['oil_features']])
y = np.array([0 if oil=='не опред.' else 1 for oil in df['Saturation']])

y = [y[i] for i in range(len(X)) if ~np.isnan(X[i][0]) and ~np.isnan(X[i][1])]
X = [list(row) for row in X if ~np.isnan(row[0]) and ~np.isnan(row[1])]
y = [y[i] for i in range(len(X)) if np.isfinite(X[i][0]) and np.isfinite(X[i][1])]
X = [list(row) for row in X if np.isfinite(row[0]) and np.isfinite(row[1])]

In [22]:
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, make_scorer
from sklearn.model_selection import ShuffleSplit, cross_val_score

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
def score(model, X, y, cv):
    scores = cross_val_score(model, X, y,
                              cv=cv,
                              scoring=make_scorer(accuracy_score))
    return scores.mean()

In [23]:
ada = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),
                         algorithm="SAMME",
                         n_estimators=200, 
                         learning_rate=1, random_state=0)
print('AdaBoost: ', score(ada, X, y, cv))

rfc = RandomForestClassifier(n_estimators=200, random_state=0)
print('RandomForestClassifier: ', score(rfc, X, y, cv))

gbc = GradientBoostingClassifier(n_estimators=200, random_state=0)
print('GradientBoostingClassifier: ', score(gbc, X, y, cv))

AdaBoost:  0.8479885057471265
RandomForestClassifier:  0.8997126436781608
GradientBoostingClassifier:  0.8862068965517242


In [25]:
print(ada.fit(X,y).feature_importances_)
print(rfc.fit(X,y).feature_importances_)
print(gbc.fit(X,y).feature_importances_)

[0.23732624 0.07410708 0.24215914 0.12266758 0.30224408 0.02149588]
[0.23532901 0.19056155 0.17376273 0.14123809 0.23916965 0.01993897]
[0.59339555 0.08069663 0.17160018 0.09158046 0.05759036 0.00513682]
